<?php
$Bloky = array(

// mix
0,"Pergola",
4,"pergola",
0,"Kamenné zdi a bazén",
5,"pred-po",
0,"Zpevnění svahu",
3,"svah",
0,"Zahradní domek",
4,"veskrnova",
0,"Altán",
6,"vyska-altan",
0,"Budujeme",
4,"kolacek",
2,"kolacekb",
3,"kolacekc",
3,"kolacekd",
0,"Schodiště",
4,"loukotovi",
0,"Usazování kamenů",
3,"vyska-kameny",
0,"Zídky ve dvoře",
4,"zelezny",
0,"...",
7,"ruzne",
3,"ruzneb",
);
?>
