<?php
$PocetBloku = 27;
$Bloky =  array(
0,"Střešní zahrady",
	7,"stra",
	6,"strb",
	1,"strc",
0,"Svahy",
	3,"svah",
0,"Stromy",
	3,"tree",
0,"Výsadba",
	2,"vysad",
0,"Příprava půdy",
	1,"pripu",
0,"Projekce",
	1,"proj",
0,"Skalky",
	4,"skal",
0,"Údržba zahrad",
	1,"udrz",
0,"Terénní úpravy",
	2,"uptr",
	0,"",
	4,"uptra",
	0,"",
	3,"uptrb",
0,"Trávníky",
	2,"trav"
);
?>
