<?php
$Bloky = array(
//0,"Zahrada pod lesem",
-1,"Projekce v roce 2000 - terénní úpravy, dlažby, zídky schodiště, oplocení a&nbsp;umístění bazénu. Pro pohledové odstínění prostoru u&nbsp;bazénu byla navržena stěna z&nbsp;kamenných sloupků a&nbsp;treláží. Pro začlenění do&nbsp;zahrady je celá doplněná lanky pro popínavé rostliny, kovovými mřížkami pro růže a&nbsp;pergolou, stínící posezení u&nbsp;bazénu. Zároveň s&nbsp;úpravou terénu bylo založeno jezírko s&nbsp;kaskádovitým přítokem od pramene nad svahem.<br />  Zahrada byla realizována během několika let.",
0,"Procházka kolem domu",
11,"",
9,"a",
5,"b",
6,"c",
);
?>
