<?php
$Bloky = array(

// mix
-1,"Byla navržena a zakládána v letech 2006-2007. Součástí návrhu byly úpravy terénu, umístění kamenných prvků, výsadeb, dřevěných staveb a jezírka. Na malém prostoru pozemku bylo velké a běžnými prostředky těžko řešitelné převýšení. Sklon byl přivrácený k domu a pro založení zahrady japonského typu ideální.",
4,"",
-1,"Je dobře vidět, že na členitém pozemku lze vytvořit mnohem zajímavější řešení prostoru, než na rovině. Výsledná kompozice skýtá mnoho různých pohledů, funkčních prostor a velkou proměnlivost během roku a je krásnou kulisou pro pozorování z interiéru domu. Již po krátké době po založení klade zahrada jen malé nároky na údržbu.",
20,"a",
);
?>
