<?php
$Bloky = array(
//0,"Zahrada v otevřené krajině",
-1,"U budovy původního statku je dřevěná terasa pro rodinné a přátelské posezení u krbu, u přístavby s vnitřním bazénem je umístěna vířivka s posezením na obloukové opěrné zídce. Obě pobytové terasy jsou od vstupního chodníku přístupné dřevěným mostem přes jezírko. Celá kompozice je pohledově orientovaná k domu a vnitřnímu prostoru bazénové haly. Řešení využívá sklon terénu, jezírko má přítok korytem potůčku od umělého pramene. V době, kdy bude výsadba vzrostlejší, bude soukromý prostor uzavřen před přímým pohladem od brány. Zahrada byla navržena a založena v roce 2004.",
6,"",
7,"a",
13,"b",
);
?>
