<?php
$Bloky = array(
-1,"Projekce a realizace v letech 2006-2007. Základem bylo vytvořit chráněný obytný prostor. Ve vstupní části byly navrženy dřevěné konstrukce pro popínavé rostliny. Prostor za domem byl rozčleněn terénním násypem s vyšším osázením na nějž navazuje stavební úprava-dělicí stěna s průchodem a přilehlým zahradním domkem, ve kterém je i technologie bazénu. Stěna se za domkem lomí a tvoří zeď oplocení po celé délce hranice na této straně pozemku. V prostoru za zdí je umístěn bazén. Prostor je úplně uzavřen od vnějšího prostoru a to i když je řada sousedních domů o cca 1 podlaží výše. Do úzkého prostoru před domem je situováno jezírko s můstky.",
5,"",
0,"&nbsp;",
6,"a",
0,"&nbsp;",
7,"b",
);
?>
